version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/packages/dialogflow-es"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/examples/dialogflow"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/examples/giphy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "np,"
    directory: "/examples/hello-http"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/examples/hello-pubsub"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "npm"
    directory: "/examples/poll"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
