on:
  release:
    types: [created]
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://wombat-dressing-room.appspot.com'
      - run: |
          npm ci
          npm compile
          npm publish --workspace packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.WOMBAT_DRESSING_ROOM_TOKEN}}
